name: colorfulbox

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2.3.2

      - name: Use Node.js 12
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      
      - name: Install dependencies
        run: |
          cd themes/tella
          npm install

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.1'
          extended: true

      - name: Build
        run: hugo --theme=tella --gc --minify

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          ftp-server: ftp.wmsc.cfbx.jp
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./public/
          server-dir: public_html/tclb.cf/